"""CLI entry point for Cozmo AI indoor scanning pipeline.

Commands:
    cozmo run --input DIR --out DIR [--drift-correction]
    cozmo benchmark --runs DIR --ground-truth CSV --out DIR
    cozmo calibrate --runs DIR --ground-truth CSV --out DIR
    cozmo fixloop --input DIR --out DIR
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.table import Table

from cozmo import __version__
from cozmo.bench.gates import Status, format_table, gate_repeatability, score_capture
from cozmo.bench.groundtruth import (
    collect_residuals,
    load_ground_truth,
    resolve_capture_id,
)
from cozmo.uncertainty.calibration import fit_quantiles
from cozmo.config import PipelineConfig
from cozmo.io import load_capture
from cozmo.pipeline import reconstruct
from cozmo.pipeline.lidar import MANIFEST_FILENAME, build_run_manifest
from cozmo.render.plan import render_svg, save_plan_image
from cozmo.schema import PropertyPlan

app = typer.Typer(
    name="cozmo",
    help="Cozmo AI: Multi-tier indoor capture to dimensioned floor plan & scope engine.",
    add_completion=False,
    no_args_is_help=True,
)
console = Console()


def _version_callback(value: bool) -> None:
    if value:
        console.print(f"[bold cyan]Cozmo AI Pipeline[/bold cyan] v{__version__}")
        raise typer.Exit()


@app.callback()
def main(
    version: Optional[bool] = typer.Option(
        None, "--version", "-v", callback=_version_callback, is_eager=True, help="Show version."
    )
) -> None:
    """Cozmo AI capture-to-plan pipeline."""
    pass


def _refuse_broken_plan(plan) -> None:
    """Stop before writing a plan whose ids name things it does not contain."""
    problems = plan.reference_problems()
    if problems:
        console.print("[bold red]The plan refers to ids it does not contain, so it was not written:[/bold red]")
        for problem in problems[:20]:
            console.print(f"  {problem}")
        raise typer.Exit(code=1)


@app.command()
def run(
    input_dir: Path = typer.Option(
        ..., "--input", "-i", help="Capture directory containing sensor data or photos.", exists=True
    ),
    out_dir: Path = typer.Option(
        ..., "--out", "-o", help="Output directory for plan.json and rendered floor plan."
    ),
    drift_correction: bool = typer.Option(
        True, "--drift-correction/--no-drift-correction", help="Enable pose graph drift correction."
    ),
    # The drift ablation the brief asks for has two axes, not one: the pose graph and the
    # plane-anchored correction that follows it. `snap_walls_to_frame` was reachable from
    # the library but not from the command line, so two rows of the reported four-way
    # ablation could not be regenerated by any documented command.
    snap_walls: bool = typer.Option(
        True,
        "--snap-walls/--no-snap-walls",
        help="Rotate near-frame walls onto the dominant building frame.",
    ),
    refine_rooms: bool = typer.Option(
        True,
        "--refine-rooms/--no-refine-rooms",
        help="Remove floor the scan says is not there: a stairwell, the far end of a room seen "
        "from its doorway, a walled space nobody saw into.",
    ),
    voxel_size: Optional[float] = typer.Option(
        None,
        "--voxel-size",
        help="Voxel size in metres for cloud fusion. Defaults to the pipeline configuration.",
    ),
    max_keyframes: Optional[int] = typer.Option(
        None, "--max-keyframes", help="Maximum keyframes to subsample from large sequence."
    ),
    verbose: bool = typer.Option(False, "--verbose", help="Enable verbose log output."),
) -> None:
    """Run full reconstruction pipeline on one capture directory."""
    logging.basicConfig(
        level=logging.INFO if verbose else logging.WARNING,
        format="%(levelname)-7s %(name)s: %(message)s",
    )

    console.print(f"[bold blue]Loading capture:[/bold blue] {input_dir}")
    source = load_capture(input_dir)
    console.print(f"Detected Tier: [bold green]{source.meta.tier.value.upper()}[/bold green] ({source.meta.frame_count} frames/images)")

    # Defaults live in PipelineConfig and nowhere else. The CLI previously hardcoded a
    # voxel size of 0.05 while the configuration said 0.02, so the same capture gave
    # different answers through the command line and through the library -- which makes
    # every reported number ambiguous about which path produced it.
    config = PipelineConfig(
        drift_correction=drift_correction, snap_walls_to_frame=snap_walls, refine_rooms=refine_rooms
    )
    if voxel_size is not None:
        config = config.with_overrides(voxel_m=voxel_size)
    if max_keyframes is not None:
        config = config.with_overrides(max_keyframes=max_keyframes)

    console.print("[bold blue]Running 3D reconstruction and semantic extraction...[/bold blue]")
    result = reconstruct(source, config=config)
    plan = result.plan
    _refuse_broken_plan(plan)

    out_dir.mkdir(parents=True, exist_ok=True)
    plan_json_path = out_dir / "plan.json"
    plan_json_path.write_text(plan.model_dump_json(indent=2))
    console.print(f"[bold green]Saved plan JSON:[/bold green] {plan_json_path}")

    # The manifest is what makes a reported number traceable to the run that produced it:
    # git commit, config, input hash, timings. It existed as a function with no callers, so
    # every run so far was unattributable -- which is exactly the reproducibility the brief
    # asks the submission to demonstrate.
    manifest = build_run_manifest(source, result, input_dir)
    manifest["config"] = {
        k: (str(v) if isinstance(v, Path) else v)
        for k, v in config.__dict__.items()
    }
    (out_dir / MANIFEST_FILENAME).write_text(json.dumps(manifest, indent=2, default=str))
    console.print(f"[bold green]Saved run manifest:[/bold green] {out_dir / MANIFEST_FILENAME}")

    svg_path = out_dir / "plan.svg"
    png_path = out_dir / "plan.png"
    svg_content = render_svg(plan, result.artifacts)
    svg_path.write_text(svg_content)
    save_plan_image(plan, result.artifacts, png_path)
    console.print(f"[bold green]Rendered 2D floor plan:[/bold green] {png_path}")

    # Display summary table
    table = Table(title=f"Property Plan Summary ({plan.capture_id})")
    table.add_column("Property Area", style="cyan")
    table.add_column("Rooms", style="magenta")
    table.add_column("Damage Regions", style="yellow")
    table.add_column("Scope Line Items", style="green")
    table.add_column("Runtime", style="dim")

    table.add_row(
        f"{plan.total_floor_area.value:.2f} m²",
        str(len(plan.rooms)),
        str(len(plan.damage)),
        str(len(plan.scope_items)),
        f"{plan.runtime_seconds:.2f} s",
    )
    console.print(table)


@app.command()
def fixloop(
    input_dir: Path = typer.Option(
        ..., "--input", "-i", help="Capture directory to run with wall snapping off and on."
    ),
    out_dir: Path = typer.Option(
        ..., "--out", "-o", help="Output directory for before_run.json (snapping off) and after_run.json (snapping on)."
    ),
) -> None:
    """Wall-snapping ablation: the same capture with snapping to the building frame off, then on.

    Not the Part 4 fix loop. Both of its rounds, their declarations and their before and after
    runs are in `fixloop/`, and neither was a snapping change.
    """
    console.print("[bold blue]Running the wall-snapping ablation...[/bold blue]")
    source = load_capture(input_dir)
    
    # Walls left where they were measured.
    cfg_before = PipelineConfig(snap_walls_to_frame=False)
    res_before = reconstruct(source, config=cfg_before)

    # Walls within the snapping tolerance rotated onto the building frame, as `cozmo run` does.
    cfg_after = PipelineConfig(snap_walls_to_frame=True)
    res_after = reconstruct(source, config=cfg_after)

    _refuse_broken_plan(res_before.plan)
    _refuse_broken_plan(res_after.plan)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "before_run.json").write_text(res_before.plan.model_dump_json(indent=2))
    (out_dir / "after_run.json").write_text(res_after.plan.model_dump_json(indent=2))

    console.print(f"[bold green]Ablation runs written to {out_dir}[/bold green]")
    console.print("  - [cyan]before_run.json[/cyan] (snapping off)")
    console.print("  - [cyan]after_run.json[/cyan] (snapping on, the default)")


def parse_repeat_pairs(values: list[str]) -> list[list[str]]:
    """Run-name pairs from `--repeat`, which may be given more than once.

    One pair used to be the limit, so a room walked on its own could not be scored against the
    same room inside a whole-flat walk while the two whole-flat walks were scored against each
    other.
    """
    pairs: list[list[str]] = []
    for value in values:
        ids = [part.strip() for part in value.split(",") if part.strip()]
        if len(ids) != 2:
            raise typer.BadParameter(f"--repeat takes two run names separated by a comma, got {value!r}")
        pairs.append(ids)
    return pairs


@app.command()
def benchmark(
    runs_dir: Path = typer.Option(
        ..., "--runs", "-r", help="Directory of run outputs, one subdirectory per capture."
    ),
    ground_truth: Path = typer.Option(
        ..., "--ground-truth", "-g", help="Ground truth CSV, tape or laser."
    ),
    out_dir: Path = typer.Option(
        Path("reports/benchmark"), "--out", "-o", help="Where to write the gate table."
    ),
    room_map: Optional[Path] = typer.Option(
        None, "--room-map", help="JSON mapping plan room ids to ground-truth room names."
    ),
    repeat: Optional[list[str]] = typer.Option(
        None,
        "--repeat",
        help="Two run names separated by a comma, scored against each other for repeatability. "
        "Give the option again to score another pair.",
    ),
) -> None:
    """Score every run against measured ground truth and print the gate table.

    A gate with no ground truth behind it is reported as not evaluated. It is never
    reported as passed, because a table of green rows that were never checked is worse
    than no table at all.
    """
    truth = load_ground_truth(ground_truth, room_map)
    if not truth.records:
        console.print(
            f"[bold yellow]No ground truth found in {ground_truth}.[/bold yellow] "
            "Every accuracy gate will be reported as not evaluated."
        )

    plans: dict[str, PropertyPlan] = {}
    for path in sorted(runs_dir.glob("*/plan.json")):
        plan = PropertyPlan(**json.loads(path.read_text()))
        plans[path.parent.name] = plan
    if not plans:
        console.print(f"[bold red]No plan.json found under {runs_dir}[/bold red]")
        raise typer.Exit(1)

    results = []
    for name, plan in plans.items():
        results.extend(score_capture(plan, truth, resolve_capture_id(plan, name, truth)))

    for ids in parse_repeat_pairs(repeat or []):
        chosen = [plans[i] for i in ids if i in plans]
        results.append(gate_repeatability(chosen, truth, ids))

    table = format_table(results)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "gate_table.txt").write_text(table + "\n")
    (out_dir / "results.json").write_text(
        json.dumps(
            [
                {
                    "gate": r.gate, "scope": r.scope, "tier": r.tier,
                    "measured": r.measured, "threshold": r.threshold,
                    "status": r.status.value, "detail": r.detail,
                }
                for r in results
            ],
            indent=2,
        )
    )
    console.print(table)
    console.print(f"\n[bold green]Written to {out_dir}[/bold green]")
    if any(r.status is Status.FAIL for r in results):
        raise typer.Exit(2)


@app.command()
def calibrate(
    runs_dir: Path = typer.Option(
        ..., "--runs", "-r", help="Directory of run outputs, one subdirectory per capture."
    ),
    ground_truth: Path = typer.Option(
        ..., "--ground-truth", "-g", help="Ground truth CSV, tape or laser."
    ),
    out_dir: Path = typer.Option(
        Path("calibration"), "--out", "-o", help="Where to write intervals.json."
    ),
    room_map: Optional[Path] = typer.Option(
        None, "--room-map", help="JSON mapping plan room ids to ground-truth room names."
    ),
    coverage: float = typer.Option(0.90, "--coverage", help="Nominal interval coverage."),
) -> None:
    """Fit split-conformal interval quantiles from measured residuals.

    This command previously ignored both of its arguments and wrote a fixed table of
    quantiles labelled as conformal calibration. Those numbers then flowed into every
    measurement in every plan as a calibrated interval, which made the single field a
    reader uses to tell a calibrated interval from a guess into a falsehood. It now fits
    from residuals or writes nothing.
    """
    truth = load_ground_truth(ground_truth, room_map)
    if not truth.records:
        console.print(
            f"[bold red]No ground truth in {ground_truth}.[/bold red] "
            "Nothing can be calibrated; intervals stay propagated or prior and say so."
        )
        raise typer.Exit(1)

    residuals: dict = {}
    used = 0
    for path in sorted(runs_dir.glob("*/plan.json")):
        plan = PropertyPlan(**json.loads(path.read_text()))
        capture_id = resolve_capture_id(plan, path.parent.name, truth)
        for key, pairs in collect_residuals(plan, truth, capture_id).items():
            residuals.setdefault(key, []).extend(pairs)
            used += len(pairs)

    if not residuals:
        console.print(
            "[bold red]No residuals could be formed.[/bold red] The ground truth and the "
            "plans share no rooms; check --room-map."
        )
        raise typer.Exit(1)

    book = fit_quantiles(residuals, coverage=coverage, source=f"{ground_truth} via {runs_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)
    target = out_dir / "intervals.json"
    book.save(target)

    table = Table(title=f"Conformal quantiles fitted from {used} residuals")
    table.add_column("tier"); table.add_column("quantity"); table.add_column("n")
    table.add_column("quantile"); table.add_column("relative"); table.add_column("empirical")
    for (tier, quantity), entry in sorted(book.entries.items()):
        table.add_row(
            tier, quantity, str(entry.n_calibration),
            f"{entry.quantile:.4f}", "yes" if entry.relative else "no",
            f"{entry.empirical_coverage:.0%}",
        )
    console.print(table)
    skipped = {k for k in residuals if k not in book.entries}
    if skipped:
        console.print(
            "[yellow]Not fitted (fewer than the finite-sample correction allows): "
            + ", ".join(f"{t}/{q}" for t, q in sorted(skipped))
            + ". These keep propagated intervals.[/yellow]"
        )
    console.print(f"[bold green]Written to {target}[/bold green]")


if __name__ == "__main__":
    app()
